import { 
  Send, 
  Upload, 
  Download, 
  Compass, 
  Home, 
  User, 
  Menu, 
  X, 
  Star,
  Save,
  StarHalf,
  Shield, 
  Link, 
  Coins, 
  Info, 
  Check, 
  ArrowRight, 
  ArrowLeft, 
  FileText, 
  File, 
  FilePen, 
  FileImage, 
  FileAudio,
  FileVideo, 
  FileArchive, 
  MessageCircle, 
  Copy, 
  ExternalLink, 
  Trash, 
  MoreHorizontal, 
  Clock as Time, 
  Flame as Fire, 
  BarChart,
  Wallet, 
  FileX, 
  Loader, 
  Search,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  List as FileList,
  Files,
  Pencil
} from "lucide-react";

export const Icons = {
  logo: Send,
  send: Send,
  upload: Upload,
  download: Download,
  compass: Compass,
  home: Home,
  user: User,
  menu: Menu,
  x: X,
  star: Star,
  starFill: (props) => (
    <Star {...props} fill="currentColor" />
  ),
  starHalfFill: StarHalf,
  shield: (props) => (
    <Shield {...props} fill="currentColor" />
  ),
  link: Link,
  money: Coins,
  info: Info,
  check: Check,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  file: File,
  fileText: FileText,
  filePdf: FilePen,
  fileImage: FileImage,
  fileAudio: FileAudio,
  fileVideo: FileVideo,
  fileArchive: FileArchive,
  fileSpreadsheet: (props) => (
    <File {...props} />
  ),
  fileList: FileList,
  fileX: FileX,
  files: Files,
  messageCircle: MessageCircle,
  copy: Copy,
  externalLink: ExternalLink,
  trash: Trash,
  moreHorizontal: MoreHorizontal,
  time: Time,
  fire: Fire,
  barChart: BarChart,
  wallet: Wallet,
  loader: Loader,
  search: Search,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  pencil: Pencil,
  save: Save,
};
